task:
    # Basic metadata:
    name: build-all
    # The build machine:
    container:
        image: gcc:latest
    # Instructions:
    make_clean: make clean
    make_script: make kernel
    kernel_artifacts:
        path: kernel
